if(isNil "server")then{hint "PLACE A GAME LOGIC NAMED SERVER!";};
EOSspawnV=compile preprocessFileLineNumbers "eos\fn\veh.sqf";
EOSgrpHandlers=compile preprocessFileLineNumbers "eos\fn\setSkill.sqf";
EOSfindSafePos=compile preprocessFileLineNumbers "eos\fn\findSafePos.sqf";
EOSspawnGrp=compile preprocessFile "eos\fn\inf.sqf";
EOSsetCargo=compile preprocessFile "eos\fn\cargo.sqf";
EOSpat=compile preprocessFile "eos\fn\patrol.sqf";
SHKpos=compile preprocessFile "eos\fn\pos.sqf";
SHKfillHouse=compile preprocessFileLineNumbers "eos\fn\housePos.sqf";
EOSgetUnitPool=compile preprocessFileLineNumbers "eos\unitPools.sqf";
call compile preprocessFileLineNumbers "eos\aiSkill.sqf";
EOSDAct={private["_mkr"];
_mkr=(_this select 0);
{_x setMarkerColor "colorBlack";_x setMarkerAlpha 0;}forEach _mkr;};
EOSdbug={private["_note"];
_mkr=(_this select 0);_n=(_this select 1);_note=(_this select 2);_pos=(_this select 3);
_mkrID=format["%3:%1,%2",_mkr,_n,_note];
deleteMarker _mkrID;
_dbugMkr=createMarker[_mkrID,_pos];
_mkrID setMarkerType "Mil_dot";_mkrID setMarkerColor "colorBlue";_mkrID setMarkerText _mkrID;_mkrID setMarkerAlpha 0.5;};