private["_parameters"];
switch(true)do{
case(isCUPV):{
_parameters=[
["SIDE",civilian],
["VEHICLES",["CUP_C_Datsun_Tubeframe","CUP_C_Datsun","CUP_C_Datsun_Plain","CUP_C_Datsun_Covered","CUP_C_Datsun_4seat","CUP_C_Skoda_White_CIV","CUP_C_Skoda_Blue_CIV","CUP_C_Skoda_Red_CIV","CUP_C_Skoda_Green_CIV","CUP_C_Golf4_black_Civ","CUP_C_Golf4_white_Civ","CUP_C_UAZ_Unarmed_TK_CIV","CUP_C_LR_Transport_CTK","CUP_C_Ural_Civ_01","CUP_C_Ural_Open_Civ_01","CUP_C_Ikarus_TKC"]],
["VEHICLES_COUNT",6],
["MIN_SPAWN_DISTANCE",1000],
["MAX_SPAWN_DISTANCE",1800],
["MIN_SKILL",0],
["MAX_SKILL",0],
["DEBUG",false]];};
case(isRHSRF):{
_parameters=[
["SIDE",civilian],
["VEHICLES",["RHS_Ural_Open_Civ_01","RHS_Ural_Civ_01","RHS_Ural_Open_Civ_02","RHS_Ural_Civ_02","RHS_Ural_Open_Civ_03","RHS_Ural_Civ_03","C_Offroad_02_unarmed_F","C_Hatchback_01_F","C_SUV_01_F"]],
["VEHICLES_COUNT",6],
["MIN_SPAWN_DISTANCE",1000],
["MAX_SPAWN_DISTANCE",1800],
["MIN_SKILL",0],
["MAX_SKILL",0],
["DEBUG",false]];};
default{
_parameters=[
["SIDE",civilian],
["VEHICLES",["C_Offroad_01_F","C_Offroad_01_repair_F","C_Quadbike_01_F","C_Hatchback_01_F","C_Hatchback_01_sport_F","C_SUV_01_F","C_Van_01_transport_F","C_Van_01_box_F","C_Van_01_fuel_F"]],
["VEHICLES_COUNT",6],
["MIN_SPAWN_DISTANCE",1000],
["MAX_SPAWN_DISTANCE",1800],
["MIN_SKILL",0],
["MAX_SKILL",0],
["DEBUG",false]];};};
_parameters spawn civTraffic_StartTraffic;